set_property PACKAGE_PIN D4 [get_ports ser_out]
set_property PACKAGE_PIN E3 [get_ports clk_in]
set_property PACKAGE_PIN V10 [get_ports Load]
set_property PACKAGE_PIN U11 [get_ports reset]
set_property PACKAGE_PIN U12 [get_ports {S[1]}]
set_property PACKAGE_PIN H6 [get_ports {S[0]}]
set_property PACKAGE_PIN J15 [get_ports {data_board[0]}]
set_property PACKAGE_PIN L16 [get_ports {data_board[1]}]
set_property PACKAGE_PIN M13 [get_ports {data_board[2]}]
set_property PACKAGE_PIN R15 [get_ports {data_board[3]}]
set_property PACKAGE_PIN R17 [get_ports {data_board[4]}]
set_property PACKAGE_PIN T18 [get_ports {data_board[5]}]
set_property PACKAGE_PIN U18 [get_ports {data_board[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_board[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_board[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_board[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_board[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_board[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_board[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_board[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_board[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports Load]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports ser_out]
set_property PACKAGE_PIN R13 [get_ports {data_board[7]}]


set_property PACKAGE_PIN H17 [get_ports check]
set_property IOSTANDARD LVCMOS33 [get_ports check]

